ccflags-y := -Iinclude/drm -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=vfpv3-d16 -ftree-vectorize -mfloat-abi=hard -ffast-math --param l2-cache-size=1024 --param l1-cache-size=32 --param l1-cache-line-size=128 -ftree-vectorize -funswitch-loops -fmodulo-sched -fivopts -ftree-loop-ivcanon -ftree-loop-im -fgcse-after-reload -fgcse-sm -fgcse-las -marm -march=armv7-a 

obj-y			+= drm/ vga/ stub/
